### ISSUE TITLE
Jwt Secret의 경우 환경변수로 관리하는 것이 좋아보입니다.

### ISSUE THREAD

**Issue by whdgnszz1** [jane5am/Streaming#2]
# 이슈사항
Jwt secret의 내용의 application.yml파일에 그대로 올라와있는 것을 확인했습니다.
공개하지 않아야 할 환경변수들은 기존에 DB연결을 했던 것처럼 환경변수로 바꿔주시고, 
application-dev.yml에 secretkey를 적용해서 사용하시길 바랍니다!

# 내용
- AS-IS
```yaml
spring:
  application:
    name: spring

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    
  sql:
    init:
      mode: always

jwt:
  secret: ThisStatementIsJwtSecretKeyDonotUseThisStatement
```

- TO-BE
```yaml
spring:
  application:
    name: spring

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

...

jwt:
  secret: ${JWT_SECRET_KEY}
```
